const DEFAULT_ROOM='asterra-global'
const PLAYER_TTL_MS=26000
const EVENT_TTL_MS=120000

const redisUrl=()=>process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||''
const redisToken=()=>process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN||''
const configured=()=>!!(redisUrl()&&redisToken())

function cleanRoom(){return DEFAULT_ROOM}
function cleanId(v){return String(v||'').replace(/[^\w-]/g,'').slice(0,90)}
function cleanName(v){return String(v||'Aventureiro').normalize('NFKC').replace(/[^\p{L}\p{N} _.\-]/gu,'').replace(/\s+/g,' ').trim().slice(0,24)||'Aventureiro'}
function num(v,d,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):d}
function safePlayer(raw={},id=''){return{id:cleanId(id||raw.id),name:cleanName(raw.name),x:num(raw.x,0,-5000,5000),y:num(raw.y,0,-30,100),z:num(raw.z,0,-5000,5000),r:num(raw.r,0,-Math.PI*8,Math.PI*8),level:num(raw.level,1,1,300),hp:num(raw.hp,120,0,1e9),maxHp:num(raw.maxHp,120,1,1e9),motion:String(raw.motion||'idle').slice(0,24),world:String(raw.world||'open').slice(0,90),guildRank:String(raw.guildRank||'E').slice(0,8),mountActive:!!raw.mountActive,classId:String(raw.classId||'mercenary_swordsman').slice(0,48),seq:num(raw.seq,0,0,0xffffffff),lastSeen:num(raw.lastSeen,Date.now(),0,Number.MAX_SAFE_INTEGER)}}
function keys(room){return{players:`sa:room:${room}:players`,events:`sa:room:${room}:events`,parties:`sa:room:${room}:parties`,playerParty:`sa:room:${room}:playerParty`,enemies:`sa:room:${room}:enemies`}}

async function redis(command){const r=await fetch(redisUrl(),{method:'POST',headers:{Authorization:`Bearer ${redisToken()}`,'Content-Type':'application/json'},body:JSON.stringify(command),cache:'no-store'});if(!r.ok)throw new Error(`redis_${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
async function pipeline(commands){const r=await fetch(`${redisUrl().replace(/\/$/,'')}/pipeline`,{method:'POST',headers:{Authorization:`Bearer ${redisToken()}`,'Content-Type':'application/json'},body:JSON.stringify(commands),cache:'no-store'});if(!r.ok)throw new Error(`redis_pipeline_${r.status}`);const j=await r.json();return Array.isArray(j)?j.map(x=>x?.result):[]}
function hashPairs(arr){const o={};for(let i=0;i<(arr||[]).length;i+=2)o[arr[i]]=arr[i+1];return o}
async function getPlayer(room,id){const raw=await redis(['HGET',keys(room).players,id]);if(!raw)return null;try{return safePlayer(JSON.parse(raw),id)}catch{return null}}
async function setPlayer(room,p){p.lastSeen=Date.now();await pipeline([['HSET',keys(room).players,p.id,JSON.stringify(p)],['EXPIRE',keys(room).players,120]]);return p}
async function addEvent(room,event){const now=Date.now(),member=JSON.stringify({...event,eventId:event.eventId||`${now}-${crypto.randomUUID()}`,ts:now});const k=keys(room).events;await pipeline([['ZADD',k,now,member],['ZREMRANGEBYSCORE',k,0,now-EVENT_TTL_MS],['EXPIRE',k,180]]);return now}
async function getRoster(room){const raw=await redis(['HGETALL',keys(room).players]),pairs=hashPairs(raw),now=Date.now(),players=[],stale=[];for(const [id,val] of Object.entries(pairs)){try{const p=safePlayer(JSON.parse(val),id);if(now-p.lastSeen>PLAYER_TTL_MS)stale.push(id);else players.push(p)}catch{stale.push(id)}}if(stale.length)await redis(['HDEL',keys(room).players,...stale]);return players}
async function getEvents(room,since=0,playerId=''){const raw=await redis(['ZRANGEBYSCORE',keys(room).events,Math.max(0,Number(since)||0),'+inf']);const out=[];for(const x of raw||[]){try{const e=JSON.parse(x);if(e.from===playerId)continue;if(e.to&&e.to!==playerId)continue;out.push(e)}catch{}}return out.slice(-160)}
async function setEnemyState(room,msg){const netId=String(msg.netId||'').slice(0,160),world=String(msg.world||'open').slice(0,90);if(!netId)return;const field=`${world}|${netId}`,prevRaw=await redis(['HGET',keys(room).enemies,field]);let prev=null;try{prev=prevRaw?JSON.parse(prevRaw):null}catch{}const maxHp=Math.max(1,Number(msg.maxHp)||Number(prev?.maxHp)||1),dead=!!msg.dead;let hp=dead?0:Math.max(0,Number(msg.hpAfter??msg.hp)||maxHp);if(!dead&&prev&&Number(msg.amount)>0)hp=Math.max(0,Number(prev.hp??maxHp)-Number(msg.amount));const state={netId,world,hp,maxHp,dead:dead||hp<=0,respawnAt:Math.max(0,Number(msg.respawnAt)||0),boss:!!msg.boss||!!prev?.boss,updatedAt:Date.now()};await pipeline([['HSET',keys(room).enemies,field,JSON.stringify(state)],['EXPIRE',keys(room).enemies,86400]])}
async function getEnemyStates(room){const raw=await redis(['HGETALL',keys(room).enemies]),pairs=hashPairs(raw),now=Date.now(),states=[],expired=[];for(const [field,val] of Object.entries(pairs)){try{const st=JSON.parse(val);if(st.dead&&st.respawnAt&&st.respawnAt<=now)expired.push(field);else states.push(st)}catch{expired.push(field)}}if(expired.length)await redis(['HDEL',keys(room).enemies,...expired]);return states}
async function getProfile(id){const raw=await redis(['GET',`sa:profile:${id}`]);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function saveProfile(id,name,game,updatedAt,lastLobby=''){const previous=await getProfile(id);const rec={...(previous||{}),id,name:cleanName(name),lastLobby:cleanRoom(lastLobby||previous?.lastLobby||DEFAULT_ROOM),updatedAt:num(updatedAt,Date.now(),0,Number.MAX_SAFE_INTEGER),game:game||null,lastSeen:Date.now()};await redis(['SET',`sa:profile:${id}`,JSON.stringify(rec)]);return rec}

async function partyState(room,partyId){if(!partyId)return null;const raw=await redis(['HGET',keys(room).parties,partyId]);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function saveParty(room,party){await pipeline([['HSET',keys(room).parties,party.id,JSON.stringify(party)],['EXPIRE',keys(room).parties,86400]]);return party}
async function publishParty(room,party){for(const memberId of party?.members||[])await addEvent(room,{type:'party_state',party,to:memberId})}
async function handleParty(room,id,msg){const k=keys(room);if(msg.type==='party_create'){let current=await redis(['HGET',k.playerParty,id]);if(current){const p=await partyState(room,current);return{party:p}}const party={id:`party-${crypto.randomUUID().slice(0,8)}`,leaderId:id,members:[id],totalXP:0};await pipeline([['HSET',k.playerParty,id,party.id],['EXPIRE',k.playerParty,86400]]);await saveParty(room,party);await publishParty(room,party);return{party}}
if(msg.type==='party_join'){const target=cleanId(msg.targetId),targetParty=await redis(['HGET',k.playerParty,target]);let party=targetParty?await partyState(room,targetParty):null;if(!party){party={id:`party-${crypto.randomUUID().slice(0,8)}`,leaderId:target,members:[target],totalXP:0};await pipeline([['HSET',k.playerParty,target,party.id],['EXPIRE',k.playerParty,86400]]);await saveParty(room,party)}if(party.members.includes(id))return{party};if(party.members.length>=4)return{error:'A equipe já tem 4 membros.'};party.members.push(id);await pipeline([['HSET',k.playerParty,id,party.id],['EXPIRE',k.playerParty,86400]]);await saveParty(room,party);await publishParty(room,party);return{party}}
if(msg.type==='party_leave'){const pid=await redis(['HGET',k.playerParty,id]);if(!pid)return{party:null};const party=await partyState(room,pid);await redis(['HDEL',k.playerParty,id]);if(!party)return{party:null};party.members=party.members.filter(x=>x!==id);if(!party.members.length){await redis(['HDEL',k.parties,pid]);return{party:null}}if(party.leaderId===id)party.leaderId=party.members[0];await saveParty(room,party);await publishParty(room,party);return{party:null}}
if(msg.type==='party_xp'){const amount=Math.max(0,Math.min(1000000,Math.round(Number(msg.amount)||0))),pid=await redis(['HGET',k.playerParty,id]);if(!pid){await addEvent(room,{type:'party_xp_award',amount,to:id});return{ok:true}}const party=await partyState(room,pid);if(!party){await addEvent(room,{type:'party_xp_award',amount,to:id});return{ok:true}}const roster=await getRoster(room),map=new Map(roster.map(p=>[p.id,p])),source=map.get(id);const eligible=party.members.filter(mid=>map.get(mid)?.world===source?.world);const count=Math.max(1,eligible.length),base=Math.floor(amount/count),rem=amount-base*count;party.totalXP=(party.totalXP||0)+amount;await saveParty(room,party);for(let i=0;i<eligible.length;i++)await addEvent(room,{type:'party_xp_award',amount:base+(i<rem?1:0),source:source?.name||'Equipe',partyId:party.id,to:eligible[i]});await publishParty(room,party);return{ok:true}}
return{ok:false}}

export default async function handler(req,res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(!configured())return res.status(503).json({ok:false,error:'redis_not_configured',message:'Configure UPSTASH_REDIS_REST_URL e UPSTASH_REDIS_REST_TOKEN (ou KV_REST_API_URL/KV_REST_API_TOKEN) no Vercel.',mode:'vercel-http'})
try{if(req.method==='GET'){const room=cleanRoom(req.query?.room),playerId=cleanId(req.query?.playerId),since=num(req.query?.since,0,0,Number.MAX_SAFE_INTEGER);if(req.query?.action==='status')return res.status(200).json({ok:true,configured:true,mode:'vercel-http',now:Date.now()});const [players,events,enemyStates]=await Promise.all([getRoster(room),getEvents(room,since,playerId),getEnemyStates(room)]);return res.status(200).json({ok:true,room,players,events,enemyStates,now:Date.now()})}
if(req.method!=='POST')return res.status(405).json({ok:false,error:'method_not_allowed'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),room=cleanRoom(body.room),id=cleanId(body.playerId);if(!id)return res.status(400).json({ok:false,error:'missing_player_id'});const type=String(body.type||'');if(type==='hello'){const profile=await getProfile(id),effectiveRoom=cleanRoom(body.room||profile?.lastLobby||room),p=safePlayer({id,name:body.name||profile?.name||'Aventureiro',lastSeen:Date.now()},id);await setPlayer(effectiveRoom,p);if(profile){profile.lastLobby=effectiveRoom;profile.name=p.name;await redis(['SET',`sa:profile:${id}`,JSON.stringify(profile)])}else{await redis(['SET',`sa:profile:${id}`,JSON.stringify({id,name:p.name,lastLobby:effectiveRoom,updatedAt:0,game:null,lastSeen:Date.now()})])}const players=await getRoster(effectiveRoom);await addEvent(effectiveRoom,{type:'join',player:p,from:id});return res.status(200).json({ok:true,type:'welcome',id,room:effectiveRoom,players:players.filter(x=>x.id!==id),profile:{...(profile||{id,name:p.name,updatedAt:0,game:null}),lastLobby:effectiveRoom},now:Date.now()})}
if(type==='state'){const prev=await getPlayer(room,id)||safePlayer({id,name:body.name},id),incomingSeq=num(body.seq,0,0,0xffffffff);if(prev.seq&&incomingSeq&&incomingSeq<prev.seq)return res.status(200).json({ok:true,stale:true,now:Date.now()});const p=safePlayer({...prev,...body,id,lastSeen:Date.now(),seq:Math.max(prev.seq||0,incomingSeq||0)},id);await setPlayer(room,p);return res.status(200).json({ok:true,seq:p.seq,now:Date.now()})}
if(type==='ping')return res.status(200).json({ok:true,type:'pong',clientTime:num(body.clientTime,0,0,Number.MAX_SAFE_INTEGER),serverTime:Date.now(),now:Date.now()})
if(type==='profile_save'){const prev=await getPlayer(room,id),profile=await saveProfile(id,prev?.name||body.name||'Aventureiro',body.game,body.updatedAt,room);return res.status(200).json({ok:true,type:'profile_saved',updatedAt:profile.updatedAt,lastLobby:profile.lastLobby})}
if(type==='rename'){const prev=await getPlayer(room,id)||safePlayer({id},id);prev.name=cleanName(body.name);await setPlayer(room,prev);const profile=await getProfile(id);if(profile)await saveProfile(id,prev.name,profile.game,profile.updatedAt,room);await addEvent(room,{type:'state',player:prev,from:id});return res.status(200).json({ok:true,type:'renamed',name:prev.name})}
if(type==='leave'){await redis(['HDEL',keys(room).players,id]);await addEvent(room,{type:'leave',id,from:id});return res.status(200).json({ok:true})}
if(type.startsWith('party_')){const result=await handleParty(room,id,body);if(result?.error)return res.status(409).json({ok:false,type:'party_error',message:result.error});return res.status(200).json({ok:true,...result})}
if(type==='enemy_damage'||type==='enemy_dead'){if(body.hpAfter!==undefined||type==='enemy_dead')await setEnemyState(room,{...body,dead:type==='enemy_dead'||body.dead});await addEvent(room,{...body,playerId:undefined,room:undefined,from:id});return res.status(200).json({ok:true,now:Date.now()})}
if(type==='player_trade'){
  const targetId=cleanId(body.targetId)
  if(!targetId)return res.status(400).json({ok:false,error:'missing_trade_target'})
  const sender=await getPlayer(room,id)
  const roster=await getRoster(room)
  if(!roster.some(p=>p.id===targetId))return res.status(200).json({ok:false,type:'trade_error',tradeId:String(body.tradeId||'').slice(0,90),message:'Jogador não está mais conectado.'})
  const items=Array.isArray(body.items)?body.items.slice(0,20).map(it=>({
    id:String(it?.id||'').slice(0,90),name:String(it?.name||'Item').slice(0,80),type:String(it?.type||'material').slice(0,30),subtype:String(it?.subtype||'').slice(0,30),rarity:String(it?.rarity||'Comum').slice(0,20),rarityTier:num(it?.rarityTier,0,0,8),color:String(it?.color||'#cbd5e1').slice(0,20),icon:String(it?.icon||'').slice(0,8),qty:num(it?.qty,1,1,9999),value:num(it?.value,0,0,100000000),level:num(it?.level,1,1,300),upgrade:num(it?.upgrade,0,0,10),durability:num(it?.durability,0,0,1000000),maxDurability:num(it?.maxDurability,0,0,1000000),stats:it?.stats&&typeof it.stats==='object'?it.stats:{},zoneId:String(it?.zoneId||'').slice(0,30),description:String(it?.description||'').slice(0,220)
  })):[]
  const gold=num(body.gold,0,0,100000000)
  const tradeId=String(body.tradeId||`trade-${Date.now().toString(36)}`).slice(0,90)
  await addEvent(room,{type:'player_trade',tradeId,from:id,fromName:sender?.name||body.name||'Jogador',items,gold,world:String(body.world||sender?.world||'open').slice(0,90),to:targetId})
  return res.status(200).json({ok:true,type:'trade_sent',tradeId,targetId,itemCount:items.length,gold,now:Date.now()})
}
if(['combat','ability','emote'].includes(type)){await addEvent(room,{...body,playerId:undefined,room:undefined,from:id});return res.status(200).json({ok:true,now:Date.now()})}
return res.status(200).json({ok:true})
}catch(err){console.error('[multiplayer]',err);return res.status(500).json({ok:false,error:'multiplayer_internal',message:String(err?.message||err)})}}
